export type Lang = 'zh' | 'en'
export type Copy = { zh: string; en: string }
export type HypothesisStatus = 'reused' | 'pass' | 'scientific-fail' | 'blocked' | 'source' | 'no-successor'

export const artifacts = [
  { id: 'solo-safe', track: 'Solo', variant: 'Safe', model: 'Gemma 4 31B', bytes: '268,763', hash: 'a81025ac…a85a', publicResult: '1,669 / 1,669', order5: '—' },
  { id: 'solo-aggressive', track: 'Solo', variant: 'Aggressive', model: 'GPT-OSS 120B · low', bytes: '360,443', hash: 'faf8468e…e70a', publicResult: '1,669 / 1,669', order5: '—' },
  { id: 'marathon-safe', track: 'Marathon', variant: 'Safe', model: 'Gemma 4 31B', bytes: '272,898', hash: '05e3b837…f3d5c', publicResult: '1,669 / 1,669', order5: '198 / 200' },
  { id: 'marathon-aggressive', track: 'Marathon', variant: 'Aggressive', model: 'GPT-OSS 120B · low', bytes: '366,197', hash: 'c87e44bd…8c21', publicResult: '1,669 / 1,669', order5: '200 / 200' },
]

export const methods: { id: string; title: Copy; body: Copy; mark: string }[] = [
  { id: 'parse', mark: '01', title: { zh: '正規化', en: 'Normalize' }, body: { zh: '解析等式 AST、統一變數命名與方向，讓結構而不是題號決定路線。', en: 'Parse equation ASTs and canonicalize names and orientation, so structure—not row identity—selects a route.' } },
  { id: 'direct', mark: '02', title: { zh: '短證明', en: 'Short proofs' }, body: { zh: '先嘗試反身、代換、單元素與定值後果，優先產出短而可重放的 Lean 證明。', en: 'Try reflexivity, substitution, singleton, and constant consequences first, producing short replayable Lean proofs.' } },
  { id: 'models', mark: '03', title: { zh: '有限反模型', en: 'Finite countermodels' }, body: { zh: '窮舉小載體，並測試結構化運算與 645 個有來源記錄的公開有限岩漿。', en: 'Exhaust small carriers, then test structured operations and 645 provenance-bound public finite magmas.' } },
  { id: 'proof', mark: '04', title: { zh: '產生證明的搜尋', en: 'Proof-producing search' }, body: { zh: '有界引數調變、符號窄化與目標導向 beam 全程保留證明 DAG。', en: 'Bounded paramodulation, symbolic narrowing, and goal-guided beam search retain a proof DAG throughout.' } },
  { id: 'h19', mark: '05', title: { zh: 'H19 去模目標引數調變', en: 'H19 demodulating search' }, body: { zh: '唯一進入最終譜系的主要 H 系列機制：透過發現、獨立驗證與兩道無回歸門。', en: 'The principal H-series mechanism reused in the final lineage after discovery, disjoint validation, and two no-regression gates.' } },
  { id: 'h22', mark: '06', title: { zh: '有界路點控制器', en: 'Bounded waypoint controller' }, body: { zh: 'Aggressive 版本可讓模型提議型別化路點，但任何文字都必須先編譯並交給 Lean。', en: 'Aggressive variants may ask a model for typed waypoints, but all text must be compiled and checked by Lean.' } },
  { id: 'judge', mark: '07', title: { zh: 'Lean 是唯一裁判', en: 'Lean is the authority' }, body: { zh: '啟發式分數、快取與模型信心都不計分；只有 accepted certificate 才改變結果。', en: 'Heuristics, caches, and model confidence do not score. Only an accepted certificate changes the result.' } },
]

const H = (id: number, status: HypothesisStatus, zh: string, en: string) => ({ id, status, copy: { zh, en } })

export const hypotheses = [
  H(1, 'blocked', '結構性反證修補的晉升編排失敗，未晉升。', 'Promotion orchestration failed for a structural countermodel repair; nothing was promoted.'),
  H(2, 'scientific-fail', '降低引數調變規則上限；覆蓋穩定，但執行時間門檻全數未過。', 'Lowered the paramodulation rule cap; coverage held, but every runtime gate failed.'),
  H(3, 'scientific-fail', '快取 AST 遍歷；公開加速不足以透過可複用校準門。', 'Cached AST traversals; public speedup missed the reusable calibration gate.'),
  H(4, 'scientific-fail', '共享 resolution 工作；公開門透過，20k 執行門失敗。', 'Shared resolution work; public gate passed, reusable 20k runtime gate failed.'),
  H(5, 'scientific-fail', '惰性正規化方向；公開門透過，20k 執行門失敗。', 'Lazy orientation canonicalization passed public speed but failed the reusable 20k gate.'),
  H(6, 'scientific-fail', '複用變數對映；公開門透過，20k 執行門失敗。', 'Reused canonical name maps; public speed passed, reusable runtime failed.'),
  H(7, 'scientific-fail', '免 binder 遍歷的目標匹配；20k 門失敗。', 'Binder-free goal matching failed the reusable 20k runtime gate.'),
  H(8, 'scientific-fail', '索引式正規化與核心快取；20k 門失敗。', 'Indexed canonicalization and core caching failed the reusable 20k gate.'),
  H(9, 'scientific-fail', '預先解析 symbolic meets；校準譜系未支援替換生產版本。', 'Pre-resolved symbolic meets; governed calibration did not support production replacement.'),
  H(10, 'blocked', '官方 LLM 路徑以 SOLVER_ERROR 終止，遙測互相矛盾。', 'Official LLM path ended in SOLVER_ERROR with contradictory telemetry.'),
  H(11, 'no-successor', '68 個 PGAP 命中全部已被有限模型路線覆蓋。', 'All 68 PGAP semantic hits were already covered by the finite-model lane.'),
  H(12, 'scientific-fail', '來源修正後父版本已解完 1,000 題，候選增益為零。', 'After source correction, the parent solved all 1,000 rows; candidate-only gain was zero.'),
  H(13, 'source', '有序 critical-pair 來源找不到父版本 abstention。', 'Ordered critical-pair completion found no parent abstentions.'),
  H(14, 'source', '長路徑目標已被解出或成本過高，來源不可行。', 'Long-walk goals were already solved or too expensive; source infeasible.'),
  H(15, 'source', '外部 oracle 只找到 9 個 clean abstentions，低於最低 12。', 'External oracle found 9 clean abstentions, below the minimum of 12.'),
  H(16, 'source', 'Z3 最小四階反模型只有 17 列，低於最低 32。', 'Minimum-order-4 Z3 source found 17 rows, below the minimum of 32.'),
  H(17, 'source', '來源透過，但固定 oracle 只確認 10/12。', 'Source passed, but the fixed oracle confirmed only 10 of 12.'),
  H(18, 'pass', 'Vampire 傳遞證明來源透過，產生 H19 的 27/9 切分。', 'Vampire transitive-proof source passed and produced the 27/9 split for H19.'),
  H(19, 'reused', '去模目標引數調變透過發現、獨立驗證與公開安全門，進入最終譜系。', 'Demodulating goal paramodulation passed discovery, disjoint validation, and public safety; reused in the final lineage.'),
  H(20, 'scientific-fail', 'LLM 結構化證書生成未透過正向校準門。', 'Structured LLM certificate generation failed its positive calibration gate.'),
  H(21, 'blocked', '模型路點校準超時，按規則不重跑。', 'Model-waypoint calibration timed out and was not rerun.'),
  H(22, 'reused', '預算化路點控制器透過校準、獨立評估與公開安全門，成為 Aggressive fallback。', 'Budgeted waypoint controller passed calibration, disjoint evaluation, and public safety; retained as Aggressive fallback.'),
  H(23, 'scientific-fail', 'verified-frontier ranking 校準失敗。', 'Verified-frontier ranking failed calibration.'),
  H(24, 'scientific-fail', 'Gemma 部署在 H19 安全過濾階段超時。', 'Gemma deployment timed out at the H19 safety filter.'),
  H(25, 'scientific-fail', '校準透過，獨立驗證失敗。', 'Calibration passed; disjoint evaluation failed.'),
  H(26, 'scientific-fail', 'timeout-local quarantine 校準失敗。', 'Timeout-local quarantine failed calibration.'),
  H(27, 'scientific-fail', 'proof-backed waypoint graph 校準透過，獨立評估失敗。', 'Proof-backed waypoint graph passed calibration and failed disjoint evaluation.'),
  H(28, 'blocked', '多階段 certificate cascade 校準程序非零退出，未計分。', 'Multiphase certificate cascade exited nonzero in calibration and remained unscored.'),
  H(29, 'pass', '總響應邊界與 terminal capsule 透過；僅代表可靠性。', 'Total-response boundary and terminal capsule passed; reliability evidence only.'),
  H(30, 'source', 'council 來源只有 22 個 clean abstentions，低於最低 24。', 'Council source found 22 clean abstentions, below the minimum of 24.'),
  H(31, 'blocked', '選擇器請求數量超過凍結 heap 容量。', 'Selector requested more rows than the frozen heap could hold.'),
  H(32, 'blocked', '實現門透過，但 stale public audit 使 preflight 在推理前停止。', 'Implementation gates passed, but a stale public audit stopped preflight before inference.'),
  H(33, 'no-successor', 'Stage 1 方法表示 census 沒找到合格缺口。', 'Stage 1 method-representation census found no eligible gap.'),
  H(34, 'blocked', 'Lean 4.33.1 模組構建成功，自測缺少 Python 依賴。', 'Lean 4.33.1 modules built; self-harness lacked a Python dependency.'),
  H(35, 'pass', '補齊依賴後的官方 harness 與兩輪 20 題 replay 透過。', 'Dependency-complete official harness and two 20-row replays passed.'),
  H(36, 'blocked', '方法內容在凍結 manifest 前可見，治理阻斷。', 'Method-bearing content became visible before the frozen manifest; governance blocked.'),
  H(37, 'pass', '雙協議 Marathon 證書 harvesting 透過本地公開相容性。', 'Dual-protocol Marathon harvesting passed local public compatibility.'),
  H(38, 'blocked', '當前 contract 的 H22 adapter 在候選執行前被基礎設施阻斷。', 'Current-contract H22 adapter was blocked before candidate execution.'),
  H(39, 'blocked', '路徑身份版 adapter 在正確性判定前被阻斷。', 'Path-identity adapter was blocked before a correctness verdict.'),
  H(40, 'blocked', '直接工具鏈路徑可用，Marathon 呼叫在候選前失敗。', 'Direct toolchain worked, but Marathon invocation failed before candidate execution.'),
  H(41, 'blocked', '單值 CLI 修正透過 parser 邊界，完整相容仍被阻斷。', 'Single-value CLI fix passed parser boundary; full compatibility remained blocked.'),
  H(42, 'blocked', '依賴已 materialize，但 readiness 沒完成。', 'Dependencies materialized, but readiness did not complete.'),
  H(43, 'pass', '斷網、預匯入 H22 adapter 透過當前官方相容性。', 'Network-denied, preimported H22 adapter passed current-official compatibility.'),
  H(44, 'no-successor', '內容盲方法差異 census 沒有合理論證的後繼。', 'Content-blind method-delta census found no justified successor.'),
  H(45, 'scientific-fail', '獨立 full-pipeline residual cluster 機制未透過科學門。', 'Disjoint full-pipeline residual-cluster mechanism failed its scientific gate.'),
  H(46, 'no-successor', '公開來源擴充套件 census 沒有合理論證的後繼。', 'Public-source expansion census found no justified successor.'),
  H(47, 'blocked', '發現階段相關性為正，但獨立確認從未執行。', 'Discovery association was positive, but independent confirmation never ran.'),
  H(48, 'blocked', 'fresh-source 策略價值實驗的來源路徑身份有缺陷。', 'Fresh-source strategy-value experiment had a defective source-path identity.'),
  H(49, 'scientific-fail', 'verified-source 校準顯示因果價值不足。', 'Verified-source calibration found insufficient causal value.'),
  H(50, 'source', 'proof-ancestry census 的凍結來源容量不足。', 'Frozen source capacity was insufficient for the proof-ancestry census.'),
  H(51, 'blocked', 'ancestry ranking 存在治理矛盾，未計分。', 'Ancestry ranking hit a governance contradiction and remained unscored.'),
  H(52, 'blocked', 'dense progress labels 的 fixture observer 無效。', 'Dense progress labels had an invalid fixture observer.'),
  H(53, 'blocked', 'exact-production trace 的程式碼身份有效性失敗。', 'Exact-production traces failed code-identity validity.'),
  H(54, 'blocked', 'observer 錯誤使 983 列失效。', 'Observer errors invalidated 983 rows.'),
  H(55, 'blocked', '新 runner 無法保留包含舊 runner hash 的凍結身份核心。', 'A new runner could not preserve an identity core containing the old runner hash.'),
  H(56, 'blocked', '兩列超出 schema cap、五列 mismatch，未計分。', 'Two rows exceeded the schema cap and five mismatched; unscored.'),
  H(57, 'pass', '1,024 個穩定 final-rule-DAG snapshot；只證明測量可靠性與標籤容量。', '1,024 stable final-rule-DAG snapshots; measurement reliability and label capacity only.'),
  H(58, 'blocked', '現有優先序已是 total，新 tie-breaker 沒有可達決策面。', 'Existing priority was already total; the new tie-breaker had no reachable decision surface.'),
  H(59, 'blocked', '唯一零列 preflight 因 identity-key binding 失敗。', 'The sole zero-row preflight failed an identity-key binding.'),
  H(60, 'blocked', '來源已 materialize，但 observer/schema/infrastructure 門失效兩列。', 'Source materialized, but observer/schema/infrastructure gates invalidated two rows.'),
  H(61, 'source', 'fresh-family abstention enumerator 在候選前出現容量不足。', 'Fresh-family abstention enumerator hit source-capacity shortfall before candidates.'),
  H(62, 'blocked', '倉庫根與官方 evaluator 根混淆，執行基底無效。', 'Repository root and official evaluator root were confused; substrate invalid.'),
  H(63, 'blocked', '唯一 preflight 使用 Python 3.9.6 而非凍結 3.11.16，譜系關閉。', 'The sole preflight used Python 3.9.6 instead of frozen 3.11.16; lineage closed.'),
]

export const statusLabels: Record<HypothesisStatus, Copy> = {
  reused: { zh: '進入最終譜系', en: 'reused' },
  pass: { zh: '窄範圍透過', en: 'bounded pass' },
  'scientific-fail': { zh: '科學門失敗', en: 'scientific fail' },
  blocked: { zh: '阻斷／無效', en: 'blocked / invalid' },
  source: { zh: '來源不足', en: 'source shortfall' },
  'no-successor': { zh: '無合理後繼', en: 'no successor' },
}
